-- Characters used to be identified by their name alone, which meant anyone who
-- could read a name off the map could play that character. From here on a
-- character belongs to an account and only its owner can enter the world with it.

-- The existing rows are anonymous: they were created before owners existed, so
-- there is nobody to assign them to. Deliberate data loss, agreed beforehand.
DELETE FROM game_character;

CREATE TABLE account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login_key     VARCHAR(32)  NOT NULL,
    login         VARCHAR(32)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    failed_logins INTEGER      NOT NULL,
    locked_until  TIMESTAMP,
    CONSTRAINT pk_account PRIMARY KEY (id),
    CONSTRAINT uq_account_login UNIQUE (login_key)
);

ALTER TABLE game_character ADD COLUMN account_id BIGINT NOT NULL;
ALTER TABLE game_character ADD CONSTRAINT fk_character_account
    FOREIGN KEY (account_id) REFERENCES account (id);

-- Only the hash of a session token is stored: a leaked database should not hand
-- anyone a working session.
CREATE TABLE account_session (
    token_hash VARCHAR(64) NOT NULL,
    account_id BIGINT      NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    CONSTRAINT pk_account_session PRIMARY KEY (token_hash),
    CONSTRAINT fk_session_account FOREIGN KEY (account_id) REFERENCES account (id)
);
